services:
  log-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log-generator
    environment:
      LOG_LEVEL: "INFO"
      LOGS_DIR: "/var/logs/hestia"
    volumes:
      - hestia-logs:/var/logs/hestia
    working_dir: /app
    command: ["python", "/app/generate_logs.py"]
    restart: unless-stopped
    networks:
      - elastic-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    container_name: logstash
    environment:
      # Adjusted JVM options with JMX disabled
      - LS_JAVA_OPTS=-Xms1g -Xmx2g -Dlog4j2.disable.jmx=true
      - LOGSTASH_SKIP_CGROUPS_CHECK=true
      - DISABLE_CGROUPS=true
      - XPACK_MONITORING_ENABLED=false
      - LS_MONITORING_ENABLED=false
      - LS_CGROUPS_ENABLED=false
      # Fixed log level to lowercase
      - LOG_LEVEL=debug
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - hestia-logs:/var/logs/hestia
    restart: unless-stopped
    depends_on:
      es01:
        condition: service_healthy
    networks:
      - elastic-net
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://es01:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=hestia-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.security.manager.enabled=false"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=hestia-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.security.manager.enabled=false"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200,http://es02:9200
    restart: unless-stopped
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
    networks:
      - elastic-net

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-elasticsearch-datasource@5.2.0
    restart: unless-stopped
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
    networks:
      - elastic-net

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  grafana-data:
    driver: local
  hestia-logs:
    driver: local

networks:
  elastic-net:
    external: true