[project]
name = "hestia-logger"
version = "1.2.0"
description = """
HESTIA is a high-performance, structured logging system for Python applications.
Supports async logging, Elastic Stack integration, structured JSON logs, and
colorized console output.
"""
readme = "README.md"
requires-python = ">=3.10"

authors = [
  { name = "FOX Techniques", email = "ali.nabbi@fox-techniques.com" }
]

license = "Apache-2.0" 

# runtime dependencies
dependencies = [
  "python-dotenv>=1.0.1,<2.0.0",
  "coloredlogs>=15.0.1,<16.0.0",
  "elasticsearch>=8.17.2,<9.0.0",
  "python-json-logger>=3.2.1,<4.0.0",
  "fastapi>=0.115.11,<0.116.0",
  "requests>=2.32.3,<3.0.0",
  "structlog>=25.1.0,<26.0.0",
  "aiofiles>=24.1.0,<25.0.0",
  "httpx>=0.28.1,<0.29.0",
  "colorlog>=6.9.0,<7.0.0",
]

[dependency-groups]
dev = [
  "pytest>=8.3.5,<9.0.0",
  "pytest-asyncio>=0.25.3,<1.0.0",
  "tox>=4.24.2,<5.0.0",
  "yamllint>=1.36.0,<2.0.0",
]
docs = [
  "mkdocs-material>=9.6.7,<10.0.0",
]

[tool.setuptools.packages.find]
include = ["hestia_logger"]
exclude = ["services*"]