apiVersion: 1
datasources:
  - name: Hestia-Logs
    type: elasticsearch
    access: proxy
    url: http://es01:9200
    database: hestia-logs-*
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"  # Matches Elasticsearch 8.x
    isDefault: true